// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: game.proto

package gamepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NackReason int32

const (
	NackReason_NACK_REASON_UNSPECIFIED NackReason = 0
	NackReason_NACK_REASON_VERSION     NackReason = 1
	NackReason_NACK_REASON_AUTH        NackReason = 2
	NackReason_NACK_REASON_SESSION     NackReason = 3
	NackReason_NACK_REASON_INTERNAL    NackReason = 99
)

// Enum value maps for NackReason.
var (
	NackReason_name = map[int32]string{
		0:  "NACK_REASON_UNSPECIFIED",
		1:  "NACK_REASON_VERSION",
		2:  "NACK_REASON_AUTH",
		3:  "NACK_REASON_SESSION",
		99: "NACK_REASON_INTERNAL",
	}
	NackReason_value = map[string]int32{
		"NACK_REASON_UNSPECIFIED": 0,
		"NACK_REASON_VERSION":     1,
		"NACK_REASON_AUTH":        2,
		"NACK_REASON_SESSION":     3,
		"NACK_REASON_INTERNAL":    99,
	}
)

func (x NackReason) Enum() *NackReason {
	p := new(NackReason)
	*p = x
	return p
}

func (x NackReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NackReason) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (NackReason) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x NackReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NackReason.Descriptor instead.
func (NackReason) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

type Handshake struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	UserId          int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token           string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	GameSessionId   string                 `protobuf:"bytes,4,opt,name=game_session_id,json=gameSessionId,proto3" json:"game_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Handshake) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Handshake) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Handshake) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Handshake) GetGameSessionId() string {
	if x != nil {
		return x.GameSessionId
	}
	return ""
}

type PlayerMove struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MapId          string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X              float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y              float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Trangthai      uint32                 `protobuf:"varint,4,opt,name=trangthai,proto3" json:"trangthai,omitempty"`
	Dir            int32                  `protobuf:"zigzag32,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Dau            string                 `protobuf:"bytes,6,opt,name=dau,proto3" json:"dau,omitempty"`
	Than           string                 `protobuf:"bytes,7,opt,name=than,proto3" json:"than,omitempty"`
	ChanField      string                 `protobuf:"bytes,8,opt,name=chan_field,json=chanField,proto3" json:"chan_field,omitempty"`
	TimeChoHienBay float32                `protobuf:"fixed32,9,opt,name=time_cho_hien_bay,json=timeChoHienBay,proto3" json:"time_cho_hien_bay,omitempty"`
	LechDauX       float32                `protobuf:"fixed32,10,opt,name=lech_dau_x,json=lechDauX,proto3" json:"lech_dau_x,omitempty"`
	LechDauY       float32                `protobuf:"fixed32,11,opt,name=lech_dau_y,json=lechDauY,proto3" json:"lech_dau_y,omitempty"`
	LechThanX      float32                `protobuf:"fixed32,12,opt,name=lech_than_x,json=lechThanX,proto3" json:"lech_than_x,omitempty"`
	LechThanY      float32                `protobuf:"fixed32,13,opt,name=lech_than_y,json=lechThanY,proto3" json:"lech_than_y,omitempty"`
	LechChanX      float32                `protobuf:"fixed32,14,opt,name=lech_chan_x,json=lechChanX,proto3" json:"lech_chan_x,omitempty"`
	LechChanY      float32                `protobuf:"fixed32,15,opt,name=lech_chan_y,json=lechChanY,proto3" json:"lech_chan_y,omitempty"`
	DangMangVanBay bool                   `protobuf:"varint,16,opt,name=dang_mang_van_bay,json=dangMangVanBay,proto3" json:"dang_mang_van_bay,omitempty"`
	TenVanBay      string                 `protobuf:"bytes,17,opt,name=ten_van_bay,json=tenVanBay,proto3" json:"ten_van_bay,omitempty"`
	Rong           float32                `protobuf:"fixed32,18,opt,name=rong,proto3" json:"rong,omitempty"`
	Cao            float32                `protobuf:"fixed32,19,opt,name=cao,proto3" json:"cao,omitempty"`
	Avatar         string                 `protobuf:"bytes,20,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerMove) Reset() {
	*x = PlayerMove{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMove) ProtoMessage() {}

func (x *PlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMove.ProtoReflect.Descriptor instead.
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerMove) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *PlayerMove) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMove) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerMove) GetTrangthai() uint32 {
	if x != nil {
		return x.Trangthai
	}
	return 0
}

func (x *PlayerMove) GetDir() int32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *PlayerMove) GetDau() string {
	if x != nil {
		return x.Dau
	}
	return ""
}

func (x *PlayerMove) GetThan() string {
	if x != nil {
		return x.Than
	}
	return ""
}

func (x *PlayerMove) GetChanField() string {
	if x != nil {
		return x.ChanField
	}
	return ""
}

func (x *PlayerMove) GetTimeChoHienBay() float32 {
	if x != nil {
		return x.TimeChoHienBay
	}
	return 0
}

func (x *PlayerMove) GetLechDauX() float32 {
	if x != nil {
		return x.LechDauX
	}
	return 0
}

func (x *PlayerMove) GetLechDauY() float32 {
	if x != nil {
		return x.LechDauY
	}
	return 0
}

func (x *PlayerMove) GetLechThanX() float32 {
	if x != nil {
		return x.LechThanX
	}
	return 0
}

func (x *PlayerMove) GetLechThanY() float32 {
	if x != nil {
		return x.LechThanY
	}
	return 0
}

func (x *PlayerMove) GetLechChanX() float32 {
	if x != nil {
		return x.LechChanX
	}
	return 0
}

func (x *PlayerMove) GetLechChanY() float32 {
	if x != nil {
		return x.LechChanY
	}
	return 0
}

func (x *PlayerMove) GetDangMangVanBay() bool {
	if x != nil {
		return x.DangMangVanBay
	}
	return false
}

func (x *PlayerMove) GetTenVanBay() string {
	if x != nil {
		return x.TenVanBay
	}
	return ""
}

func (x *PlayerMove) GetRong() float32 {
	if x != nil {
		return x.Rong
	}
	return 0
}

func (x *PlayerMove) GetCao() float32 {
	if x != nil {
		return x.Cao
	}
	return 0
}

func (x *PlayerMove) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type HandshakeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeAck) Reset() {
	*x = HandshakeAck{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeAck) ProtoMessage() {}

func (x *HandshakeAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeAck.ProtoReflect.Descriptor instead.
func (*HandshakeAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

type HandshakeNack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        NackReason             `protobuf:"varint,1,opt,name=reason,proto3,enum=game.NackReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeNack) Reset() {
	*x = HandshakeNack{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeNack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeNack) ProtoMessage() {}

func (x *HandshakeNack) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeNack.ProtoReflect.Descriptor instead.
func (*HandshakeNack) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeNack) GetReason() NackReason {
	if x != nil {
		return x.Reason
	}
	return NackReason_NACK_REASON_UNSPECIFIED
}

type PlayerSync struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	X              float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y              float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Trangthai      uint32                 `protobuf:"varint,4,opt,name=trangthai,proto3" json:"trangthai,omitempty"`
	Dir            int32                  `protobuf:"zigzag32,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Dau            string                 `protobuf:"bytes,6,opt,name=dau,proto3" json:"dau,omitempty"`
	Than           string                 `protobuf:"bytes,7,opt,name=than,proto3" json:"than,omitempty"`
	ChanField      string                 `protobuf:"bytes,8,opt,name=chan_field,json=chanField,proto3" json:"chan_field,omitempty"`
	TimeChoHienBay float32                `protobuf:"fixed32,9,opt,name=time_cho_hien_bay,json=timeChoHienBay,proto3" json:"time_cho_hien_bay,omitempty"`
	LechDauX       float32                `protobuf:"fixed32,10,opt,name=lech_dau_x,json=lechDauX,proto3" json:"lech_dau_x,omitempty"`
	LechDauY       float32                `protobuf:"fixed32,11,opt,name=lech_dau_y,json=lechDauY,proto3" json:"lech_dau_y,omitempty"`
	LechThanX      float32                `protobuf:"fixed32,12,opt,name=lech_than_x,json=lechThanX,proto3" json:"lech_than_x,omitempty"`
	LechThanY      float32                `protobuf:"fixed32,13,opt,name=lech_than_y,json=lechThanY,proto3" json:"lech_than_y,omitempty"`
	LechChanX      float32                `protobuf:"fixed32,14,opt,name=lech_chan_x,json=lechChanX,proto3" json:"lech_chan_x,omitempty"`
	LechChanY      float32                `protobuf:"fixed32,15,opt,name=lech_chan_y,json=lechChanY,proto3" json:"lech_chan_y,omitempty"`
	DangMangVanBay bool                   `protobuf:"varint,16,opt,name=dang_mang_van_bay,json=dangMangVanBay,proto3" json:"dang_mang_van_bay,omitempty"`
	TenVanBay      string                 `protobuf:"bytes,17,opt,name=ten_van_bay,json=tenVanBay,proto3" json:"ten_van_bay,omitempty"`
	Rong           float32                `protobuf:"fixed32,18,opt,name=rong,proto3" json:"rong,omitempty"`
	Cao            float32                `protobuf:"fixed32,19,opt,name=cao,proto3" json:"cao,omitempty"`
	Avatar         string                 `protobuf:"bytes,20,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ServerTime     int64                  `protobuf:"varint,21,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerSync) Reset() {
	*x = PlayerSync{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSync) ProtoMessage() {}

func (x *PlayerSync) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSync.ProtoReflect.Descriptor instead.
func (*PlayerSync) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerSync) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlayerSync) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerSync) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerSync) GetTrangthai() uint32 {
	if x != nil {
		return x.Trangthai
	}
	return 0
}

func (x *PlayerSync) GetDir() int32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *PlayerSync) GetDau() string {
	if x != nil {
		return x.Dau
	}
	return ""
}

func (x *PlayerSync) GetThan() string {
	if x != nil {
		return x.Than
	}
	return ""
}

func (x *PlayerSync) GetChanField() string {
	if x != nil {
		return x.ChanField
	}
	return ""
}

func (x *PlayerSync) GetTimeChoHienBay() float32 {
	if x != nil {
		return x.TimeChoHienBay
	}
	return 0
}

func (x *PlayerSync) GetLechDauX() float32 {
	if x != nil {
		return x.LechDauX
	}
	return 0
}

func (x *PlayerSync) GetLechDauY() float32 {
	if x != nil {
		return x.LechDauY
	}
	return 0
}

func (x *PlayerSync) GetLechThanX() float32 {
	if x != nil {
		return x.LechThanX
	}
	return 0
}

func (x *PlayerSync) GetLechThanY() float32 {
	if x != nil {
		return x.LechThanY
	}
	return 0
}

func (x *PlayerSync) GetLechChanX() float32 {
	if x != nil {
		return x.LechChanX
	}
	return 0
}

func (x *PlayerSync) GetLechChanY() float32 {
	if x != nil {
		return x.LechChanY
	}
	return 0
}

func (x *PlayerSync) GetDangMangVanBay() bool {
	if x != nil {
		return x.DangMangVanBay
	}
	return false
}

func (x *PlayerSync) GetTenVanBay() string {
	if x != nil {
		return x.TenVanBay
	}
	return ""
}

func (x *PlayerSync) GetRong() float32 {
	if x != nil {
		return x.Rong
	}
	return 0
}

func (x *PlayerSync) GetCao() float32 {
	if x != nil {
		return x.Cao
	}
	return 0
}

func (x *PlayerSync) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PlayerSync) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type PlayerSyncBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerSync          `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSyncBatch) Reset() {
	*x = PlayerSyncBatch{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSyncBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSyncBatch) ProtoMessage() {}

func (x *PlayerSyncBatch) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSyncBatch.ProtoReflect.Descriptor instead.
func (*PlayerSyncBatch) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerSyncBatch) GetPlayers() []*PlayerSync {
	if x != nil {
		return x.Players
	}
	return nil
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Handshake
	//	*Envelope_PlayerMove
	//	*Envelope_HandshakeAck
	//	*Envelope_HandshakeNack
	//	*Envelope_PlayerSync
	//	*Envelope_PlayerSyncBatch
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Envelope) GetPlayerMove() *PlayerMove {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PlayerMove); ok {
			return x.PlayerMove
		}
	}
	return nil
}

func (x *Envelope) GetHandshakeAck() *HandshakeAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HandshakeAck); ok {
			return x.HandshakeAck
		}
	}
	return nil
}

func (x *Envelope) GetHandshakeNack() *HandshakeNack {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HandshakeNack); ok {
			return x.HandshakeNack
		}
	}
	return nil
}

func (x *Envelope) GetPlayerSync() *PlayerSync {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PlayerSync); ok {
			return x.PlayerSync
		}
	}
	return nil
}

func (x *Envelope) GetPlayerSyncBatch() *PlayerSyncBatch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PlayerSyncBatch); ok {
			return x.PlayerSyncBatch
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Handshake struct {
	// Client → Server
	Handshake *Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type Envelope_PlayerMove struct {
	PlayerMove *PlayerMove `protobuf:"bytes,2,opt,name=player_move,json=playerMove,proto3,oneof"`
}

type Envelope_HandshakeAck struct {
	// Server → Client
	HandshakeAck *HandshakeAck `protobuf:"bytes,10,opt,name=handshake_ack,json=handshakeAck,proto3,oneof"`
}

type Envelope_HandshakeNack struct {
	HandshakeNack *HandshakeNack `protobuf:"bytes,11,opt,name=handshake_nack,json=handshakeNack,proto3,oneof"`
}

type Envelope_PlayerSync struct {
	PlayerSync *PlayerSync `protobuf:"bytes,12,opt,name=player_sync,json=playerSync,proto3,oneof"`
}

type Envelope_PlayerSyncBatch struct {
	PlayerSyncBatch *PlayerSyncBatch `protobuf:"bytes,13,opt,name=player_sync_batch,json=playerSyncBatch,proto3,oneof"`
}

func (*Envelope_Handshake) isEnvelope_Payload() {}

func (*Envelope_PlayerMove) isEnvelope_Payload() {}

func (*Envelope_HandshakeAck) isEnvelope_Payload() {}

func (*Envelope_HandshakeNack) isEnvelope_Payload() {}

func (*Envelope_PlayerSync) isEnvelope_Payload() {}

func (*Envelope_PlayerSyncBatch) isEnvelope_Payload() {}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"\x8d\x01\n" +
	"\tHandshake\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12&\n" +
	"\x0fgame_session_id\x18\x04 \x01(\tR\rgameSessionId\"\xa4\x04\n" +
	"\n" +
	"PlayerMove\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x1c\n" +
	"\ttrangthai\x18\x04 \x01(\rR\ttrangthai\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\x11R\x03dir\x12\x10\n" +
	"\x03dau\x18\x06 \x01(\tR\x03dau\x12\x12\n" +
	"\x04than\x18\a \x01(\tR\x04than\x12\x1d\n" +
	"\n" +
	"chan_field\x18\b \x01(\tR\tchanField\x12)\n" +
	"\x11time_cho_hien_bay\x18\t \x01(\x02R\x0etimeChoHienBay\x12\x1c\n" +
	"\n" +
	"lech_dau_x\x18\n" +
	" \x01(\x02R\blechDauX\x12\x1c\n" +
	"\n" +
	"lech_dau_y\x18\v \x01(\x02R\blechDauY\x12\x1e\n" +
	"\vlech_than_x\x18\f \x01(\x02R\tlechThanX\x12\x1e\n" +
	"\vlech_than_y\x18\r \x01(\x02R\tlechThanY\x12\x1e\n" +
	"\vlech_chan_x\x18\x0e \x01(\x02R\tlechChanX\x12\x1e\n" +
	"\vlech_chan_y\x18\x0f \x01(\x02R\tlechChanY\x12)\n" +
	"\x11dang_mang_van_bay\x18\x10 \x01(\bR\x0edangMangVanBay\x12\x1e\n" +
	"\vten_van_bay\x18\x11 \x01(\tR\ttenVanBay\x12\x12\n" +
	"\x04rong\x18\x12 \x01(\x02R\x04rong\x12\x10\n" +
	"\x03cao\x18\x13 \x01(\x02R\x03cao\x12\x16\n" +
	"\x06avatar\x18\x14 \x01(\tR\x06avatar\"\x0e\n" +
	"\fHandshakeAck\"9\n" +
	"\rHandshakeNack\x12(\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x10.game.NackReasonR\x06reason\"\xc7\x04\n" +
	"\n" +
	"PlayerSync\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x1c\n" +
	"\ttrangthai\x18\x04 \x01(\rR\ttrangthai\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\x11R\x03dir\x12\x10\n" +
	"\x03dau\x18\x06 \x01(\tR\x03dau\x12\x12\n" +
	"\x04than\x18\a \x01(\tR\x04than\x12\x1d\n" +
	"\n" +
	"chan_field\x18\b \x01(\tR\tchanField\x12)\n" +
	"\x11time_cho_hien_bay\x18\t \x01(\x02R\x0etimeChoHienBay\x12\x1c\n" +
	"\n" +
	"lech_dau_x\x18\n" +
	" \x01(\x02R\blechDauX\x12\x1c\n" +
	"\n" +
	"lech_dau_y\x18\v \x01(\x02R\blechDauY\x12\x1e\n" +
	"\vlech_than_x\x18\f \x01(\x02R\tlechThanX\x12\x1e\n" +
	"\vlech_than_y\x18\r \x01(\x02R\tlechThanY\x12\x1e\n" +
	"\vlech_chan_x\x18\x0e \x01(\x02R\tlechChanX\x12\x1e\n" +
	"\vlech_chan_y\x18\x0f \x01(\x02R\tlechChanY\x12)\n" +
	"\x11dang_mang_van_bay\x18\x10 \x01(\bR\x0edangMangVanBay\x12\x1e\n" +
	"\vten_van_bay\x18\x11 \x01(\tR\ttenVanBay\x12\x12\n" +
	"\x04rong\x18\x12 \x01(\x02R\x04rong\x12\x10\n" +
	"\x03cao\x18\x13 \x01(\x02R\x03cao\x12\x16\n" +
	"\x06avatar\x18\x14 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vserver_time\x18\x15 \x01(\x03R\n" +
	"serverTime\"=\n" +
	"\x0fPlayerSyncBatch\x12*\n" +
	"\aplayers\x18\x01 \x03(\v2\x10.game.PlayerSyncR\aplayers\"\xee\x02\n" +
	"\bEnvelope\x12/\n" +
	"\thandshake\x18\x01 \x01(\v2\x0f.game.HandshakeH\x00R\thandshake\x123\n" +
	"\vplayer_move\x18\x02 \x01(\v2\x10.game.PlayerMoveH\x00R\n" +
	"playerMove\x129\n" +
	"\rhandshake_ack\x18\n" +
	" \x01(\v2\x12.game.HandshakeAckH\x00R\fhandshakeAck\x12<\n" +
	"\x0ehandshake_nack\x18\v \x01(\v2\x13.game.HandshakeNackH\x00R\rhandshakeNack\x123\n" +
	"\vplayer_sync\x18\f \x01(\v2\x10.game.PlayerSyncH\x00R\n" +
	"playerSync\x12C\n" +
	"\x11player_sync_batch\x18\r \x01(\v2\x15.game.PlayerSyncBatchH\x00R\x0fplayerSyncBatchB\t\n" +
	"\apayload*\x8b\x01\n" +
	"\n" +
	"NackReason\x12\x1b\n" +
	"\x17NACK_REASON_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NACK_REASON_VERSION\x10\x01\x12\x14\n" +
	"\x10NACK_REASON_AUTH\x10\x02\x12\x17\n" +
	"\x13NACK_REASON_SESSION\x10\x03\x12\x18\n" +
	"\x14NACK_REASON_INTERNAL\x10cB@Z>github.com/DANG-PH/game-service-go/internal/protocol/pb;gamepbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_game_proto_goTypes = []any{
	(NackReason)(0),         // 0: game.NackReason
	(*Handshake)(nil),       // 1: game.Handshake
	(*PlayerMove)(nil),      // 2: game.PlayerMove
	(*HandshakeAck)(nil),    // 3: game.HandshakeAck
	(*HandshakeNack)(nil),   // 4: game.HandshakeNack
	(*PlayerSync)(nil),      // 5: game.PlayerSync
	(*PlayerSyncBatch)(nil), // 6: game.PlayerSyncBatch
	(*Envelope)(nil),        // 7: game.Envelope
}
var file_game_proto_depIdxs = []int32{
	0, // 0: game.HandshakeNack.reason:type_name -> game.NackReason
	5, // 1: game.PlayerSyncBatch.players:type_name -> game.PlayerSync
	1, // 2: game.Envelope.handshake:type_name -> game.Handshake
	2, // 3: game.Envelope.player_move:type_name -> game.PlayerMove
	3, // 4: game.Envelope.handshake_ack:type_name -> game.HandshakeAck
	4, // 5: game.Envelope.handshake_nack:type_name -> game.HandshakeNack
	5, // 6: game.Envelope.player_sync:type_name -> game.PlayerSync
	6, // 7: game.Envelope.player_sync_batch:type_name -> game.PlayerSyncBatch
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_game_proto_msgTypes[6].OneofWrappers = []any{
		(*Envelope_Handshake)(nil),
		(*Envelope_PlayerMove)(nil),
		(*Envelope_HandshakeAck)(nil),
		(*Envelope_HandshakeNack)(nil),
		(*Envelope_PlayerSync)(nil),
		(*Envelope_PlayerSyncBatch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
